#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDrivenProgEnrollmentSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OnlyTable")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetStudentName")]
		public ISingleResult<usp_GetStudentNameResult> usp_GetStudentName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountID", DbType="Int")] System.Nullable<int> accountID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountID);
			return ((ISingleResult<usp_GetStudentNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspAddAccount")]
		public int uspAddAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(255)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AddEnrollmentForm")]
		public int usp_AddEnrollmentForm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Account_ID", DbType="Int")] System.Nullable<int> account_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Last_Name", DbType="NVarChar(50)")] string last_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="First_Name", DbType="NVarChar(50)")] string first_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Middle_Name", DbType="NVarChar(50)")] string middle_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Birthdate", DbType="Date")] System.Nullable<System.DateTime> birthdate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="NVarChar(20)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Religion", DbType="NVarChar(50)")] string religion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nationality", DbType="NVarChar(50)")] string nationality, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(200)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="NVarChar(20)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Age", DbType="Int")] System.Nullable<int> age, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Birth_Place", DbType="NVarChar(100)")] string birth_Place, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Course_Type", DbType="NVarChar(50)")] string course_Type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Course_YearLevel", DbType="NVarChar(50)")] string course_YearLevel)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_ID, last_Name, first_Name, middle_Name, birthdate, gender, religion, nationality, address, phone, age, birth_Place, course_Type, course_YearLevel);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetAllStudents")]
		public ISingleResult<usp_GetAllStudentsResult> usp_GetAllStudents()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_GetAllStudentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AddSubject")]
		public int usp_AddSubject([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectName", DbType="NVarChar(100)")] string subjectName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Units", DbType="Int")] System.Nullable<int> units, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lab", DbType="NVarChar(50)")] string lab, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Time", DbType="NVarChar(50)")] string time)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subjectName, units, lab, time);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetSubjects")]
		public ISingleResult<usp_GetSubjectsResult> usp_GetSubjects()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_GetSubjectsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UpdateSubject")]
		public int usp_UpdateSubject([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectName", DbType="NVarChar(100)")] string subjectName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Units", DbType="Int")] System.Nullable<int> units, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lab", DbType="NVarChar(50)")] string lab, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Time", DbType="NVarChar(50)")] string time)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subjectName, units, lab, time);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetAvailableSubjects")]
		public ISingleResult<usp_GetAvailableSubjectsResult> usp_GetAvailableSubjects([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentID", DbType="Int")] System.Nullable<int> studentID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID);
			return ((ISingleResult<usp_GetAvailableSubjectsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AddStudentSchedule")]
		public int usp_AddStudentSchedule([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentID", DbType="Int")] System.Nullable<int> studentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectID", DbType="Int")] System.Nullable<int> subjectID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID, subjectID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetStudentInfo")]
		public ISingleResult<usp_GetStudentInfoResult> usp_GetStudentInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountID", DbType="Int")] System.Nullable<int> accountID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountID);
			return ((ISingleResult<usp_GetStudentInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetStudentSchedule")]
		public ISingleResult<usp_GetStudentScheduleResult> usp_GetStudentSchedule([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentID", DbType="Int")] System.Nullable<int> studentID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID);
			return ((ISingleResult<usp_GetStudentScheduleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UpdateUsernameAndStatusByName")]
		public int usp_UpdateUsernameAndStatusByName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentStatus", DbType="NVarChar(50)")] string studentStatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstName, lastName, username, studentStatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UpdateUsernameAndStatus")]
		public int usp_UpdateUsernameAndStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountID", DbType="Int")] System.Nullable<int> accountID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentStatus", DbType="NVarChar(50)")] string studentStatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountID, username, studentStatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_UpdateUsernameAndStatusByEmail")]
		public int usp_UpdateUsernameAndStatusByEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentStatus", DbType="NVarChar(50)")] string studentStatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, username, studentStatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetStudentName")]
		public ISingleResult<usp_GetStudentNameResult1> usp_GetStudentName1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountID", DbType="Int")] System.Nullable<int> accountID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountID);
			return ((ISingleResult<usp_GetStudentNameResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_GetStudentSubjects")]
		public ISingleResult<usp_GetStudentSubjectsResult> usp_GetStudentSubjects([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountID", DbType="Int")] System.Nullable<int> accountID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountID);
			return ((ISingleResult<usp_GetStudentSubjectsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AddAccountRecord")]
		public ISingleResult<usp_AddAccountRecordResult> usp_AddAccountRecord([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Account_ID", DbType="Int")] System.Nullable<int> account_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AcademicYear", DbType="NVarChar(50)")] string academicYear, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentMethod", DbType="NVarChar(50)")] string paymentMethod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Int")] System.Nullable<int> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Balance", DbType="Int")] System.Nullable<int> balance, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NVarChar(50)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account_ID, academicYear, paymentMethod, amount, balance, status);
			return ((ISingleResult<usp_AddAccountRecordResult>)(result.ReturnValue));
		}
	}
	
	public partial class usp_GetStudentNameResult
	{
		
		private string _First_Name;
		
		private string _Last_Name;
		
		public usp_GetStudentNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
	}
	
	public partial class usp_GetAllStudentsResult
	{
		
		private System.Nullable<int> _StudentID;
		
		private string _Name;
		
		private string _Course;
		
		private string _Phone;
		
		private string _Address;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Birthdate;
		
		private string _Gender;
		
		private string _Religion;
		
		private string _Nationality;
		
		private string _YearLevel;
		
		private string _Student_Status;
		
		private string _Username;
		
		public usp_GetAllStudentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="Int")]
		public System.Nullable<int> StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					this._StudentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(152)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="NVarChar(50)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthdate", DbType="Date")]
		public System.Nullable<System.DateTime> Birthdate
		{
			get
			{
				return this._Birthdate;
			}
			set
			{
				if ((this._Birthdate != value))
				{
					this._Birthdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="NVarChar(50)")]
		public string Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this._Religion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this._Nationality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearLevel", DbType="NVarChar(50)")]
		public string YearLevel
		{
			get
			{
				return this._YearLevel;
			}
			set
			{
				if ((this._YearLevel != value))
				{
					this._YearLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Status", DbType="NVarChar(50)")]
		public string Student_Status
		{
			get
			{
				return this._Student_Status;
			}
			set
			{
				if ((this._Student_Status != value))
				{
					this._Student_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
	}
	
	public partial class usp_GetSubjectsResult
	{
		
		private string _Subject_Name;
		
		private System.Nullable<int> _Units;
		
		private System.Nullable<int> _Lab;
		
		private string _Subject_Time;
		
		public usp_GetSubjectsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject_Name", DbType="NVarChar(50)")]
		public string Subject_Name
		{
			get
			{
				return this._Subject_Name;
			}
			set
			{
				if ((this._Subject_Name != value))
				{
					this._Subject_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Units", DbType="Int")]
		public System.Nullable<int> Units
		{
			get
			{
				return this._Units;
			}
			set
			{
				if ((this._Units != value))
				{
					this._Units = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lab", DbType="Int")]
		public System.Nullable<int> Lab
		{
			get
			{
				return this._Lab;
			}
			set
			{
				if ((this._Lab != value))
				{
					this._Lab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject_Time", DbType="NVarChar(50)")]
		public string Subject_Time
		{
			get
			{
				return this._Subject_Time;
			}
			set
			{
				if ((this._Subject_Time != value))
				{
					this._Subject_Time = value;
				}
			}
		}
	}
	
	public partial class usp_GetAvailableSubjectsResult
	{
		
		private int _SubjectID;
		
		private string _Subject;
		
		public usp_GetAvailableSubjectsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL")]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(50)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this._Subject = value;
				}
			}
		}
	}
	
	public partial class usp_GetStudentInfoResult
	{
		
		private System.Nullable<int> _Student_ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Course_Type;
		
		private string _Course_YearLevel;
		
		private string _Student_Status;
		
		public usp_GetStudentInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_ID", DbType="Int")]
		public System.Nullable<int> Student_ID
		{
			get
			{
				return this._Student_ID;
			}
			set
			{
				if ((this._Student_ID != value))
				{
					this._Student_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="NVarChar(50)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="NVarChar(50)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Type", DbType="NVarChar(50)")]
		public string Course_Type
		{
			get
			{
				return this._Course_Type;
			}
			set
			{
				if ((this._Course_Type != value))
				{
					this._Course_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_YearLevel", DbType="NVarChar(50)")]
		public string Course_YearLevel
		{
			get
			{
				return this._Course_YearLevel;
			}
			set
			{
				if ((this._Course_YearLevel != value))
				{
					this._Course_YearLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Status", DbType="NVarChar(50)")]
		public string Student_Status
		{
			get
			{
				return this._Student_Status;
			}
			set
			{
				if ((this._Student_Status != value))
				{
					this._Student_Status = value;
				}
			}
		}
	}
	
	public partial class usp_GetStudentScheduleResult
	{
		
		private string _Subject;
		
		private System.Nullable<int> _Unit;
		
		private string _Lab;
		
		private string _Schedule;
		
		public usp_GetStudentScheduleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(50)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this._Subject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="Int")]
		public System.Nullable<int> Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lab", DbType="NVarChar(50)")]
		public string Lab
		{
			get
			{
				return this._Lab;
			}
			set
			{
				if ((this._Lab != value))
				{
					this._Lab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schedule", DbType="NVarChar(50)")]
		public string Schedule
		{
			get
			{
				return this._Schedule;
			}
			set
			{
				if ((this._Schedule != value))
				{
					this._Schedule = value;
				}
			}
		}
	}
	
	public partial class usp_GetStudentNameResult1
	{
		
		private string _First_Name;
		
		private string _Last_Name;
		
		public usp_GetStudentNameResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="NVarChar(50)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="NVarChar(50)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
	}
	
	public partial class usp_GetStudentSubjectsResult
	{
		
		private string _Subject;
		
		private System.Nullable<int> _Unit;
		
		private System.Nullable<int> _Lab;
		
		public usp_GetStudentSubjectsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(50)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this._Subject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="Int")]
		public System.Nullable<int> Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lab", DbType="Int")]
		public System.Nullable<int> Lab
		{
			get
			{
				return this._Lab;
			}
			set
			{
				if ((this._Lab != value))
				{
					this._Lab = value;
				}
			}
		}
	}
	
	public partial class usp_AddAccountRecordResult
	{
		
		private System.Nullable<decimal> _NewRecordID;
		
		public usp_AddAccountRecordResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewRecordID", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> NewRecordID
		{
			get
			{
				return this._NewRecordID;
			}
			set
			{
				if ((this._NewRecordID != value))
				{
					this._NewRecordID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
