//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDrivenProgEnrollmentSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-SGTQTMFL\\SQLEXPRESS01;Initial Catalog=2324_2A_FileUploadSample" +
            ";Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificat" +
            "e=False")]
        public string _2324_2A_FileUploadSampleConnectionString {
            get {
                return ((string)(this["_2324_2A_FileUploadSampleConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-SGTQTMFL\\SQLEXPRESS01;Initial Catalog=Enrollement;Integrated S" +
            "ecurity=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string EnrollmentConnectionString {
            get {
                return ((string)(this["EnrollmentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-SGTQTMFL\\SQLEXPRESS01;Initial Catalog=OnlyTable;Integrated Sec" +
            "urity=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string OnlyTableConnectionString {
            get {
                return ((string)(this["OnlyTableConnectionString"]));
            }
        }
    }
}
